{ 'Kalte Vorspeisen': 
   [ [ 'Tzatziki (G)',
       'pikante Qarkspeise mit knoblauch, dazu Brot',
       '4,80€' ],
     [ 'Dolmadakia (G)',
       ' gefüllte Weinblätter mit Reis mit Tzatziki',
       5.6 ],
     [ 'Chtipiti (G)    ',
       'pikante Schafskäsecreme, dazu Brot ',
       '4,80€' ],
     [ 'Schafkäse (G)', 'mit Zwiebeln und Olivenöl', '6,50€' ],
     [ 'Vorspeiseteller Spezial (G)', '', '8,90€' ],
     [ 'Gebackener Schfskäse', 'mit Zwiebeln und knoblauch', '6,90€' ],
     [ 'Dicke Bohnen (G)',
       'mit geriebenem Schafskäse und Käse überbacken',
       '6,90€' ],
     [ 'Gefüllte Weinblätter (G) ',
       'mit geriebenem Schafskäse und Käse überbacken',
       '6,90€' ],
     [ 'Gegrillte Peperoni(G)', 'mit Knoblacuhsoße', '6,00€' ],
     [ 'Calamaresringe (A,C,G) ', 'mit Tzatziki', '7,50€' ],
     [ 'Zwei Garnelen Spieße (G)', 'mit Knoblauchsoße', '9,90€' ],
     [ 'Gebackener Camembert (G)', 'mit Preiselbeeren', '7,50€' ],
     [ 'Knoblauchbrot (A)', '', '3,00€' ] ],
  'Warme Vorspeisen': 
   [ [ 'Tzatziki (G)',
       'pikante Qarkspeise mit knoblauch, dazu Brot',
       '4,80€' ],
     [ 'Dolmadakia (G)',
       ' gefüllte Weinblätter mit Reis mit Tzatziki',
       5.6 ],
     [ 'Chtipiti (G)    ',
       'pikante Schafskäsecreme, dazu Brot ',
       '4,80€' ],
     [ 'Schafkäse (G)', 'mit Zwiebeln und Olivenöl', '6,50€' ],
     [ 'Vorspeiseteller Spezial (G)', '', '8,90€' ],
     [ 'Gebackener Schfskäse', 'mit Zwiebeln und knoblauch', '6,90€' ],
     [ 'Dicke Bohnen (G)',
       'mit geriebenem Schafskäse und Käse überbacken',
       '6,90€' ],
     [ 'Gefüllte Weinblätter (G) ',
       'mit geriebenem Schafskäse und Käse überbacken',
       '6,90€' ],
     [ 'Gegrillte Peperoni(G)', 'mit Knoblacuhsoße', '6,00€' ],
     [ 'Calamaresringe (A,C,G) ', 'mit Tzatziki', '7,50€' ],
     [ 'Zwei Garnelen Spieße (G)', 'mit Knoblauchsoße', '9,90€' ],
     [ 'Gebackener Camembert (G)', 'mit Preiselbeeren', '7,50€' ],
     [ 'Knoblauchbrot (A)', '', '3,00€' ] ] }